data.connectionstring = "data/Melbourne_housing_FULL.csv"
data.format = "csv"

input_query.connectionstring = "data/input.csv"
input_query.format = "csv"

model_file_location = "pickles/model.pkl"

dataframe.keep_columns = true

[[dataframe.inputs]]
name = "Suburb"
ftype = "category"
[[dataframe.inputs.encoding_steps]]
algo = "label_binarizer"
settings.file_location = "pickles/suburb_label_bin.pkl"

[[dataframe.inputs]]
name = "CouncilArea"
ftype = "category"
[[dataframe.inputs.encoding_steps]]
algo = "label_binarizer"
settings.file_location = "pickles/council_area_label_bin.pkl"

[[dataframe.inputs]]
name = "Type"
ftype = "category"
[[dataframe.inputs.encoding_steps]]
algo = "label_binarizer"
settings.file_location = "pickles/type_label_bin.pkl"

[[dataframe.outputs]]
name = "Price"